version: "3.3"

volumes:
  mysql: {}

services:
  mysqltest:
    image: mariadb:10.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "12345"
    hostname: localhost